name: Build ZMK Firmware
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:3.5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: zmk-config-notbroken

      - name: Checkout ZMK
        uses: actions/checkout@v4
        with:
          repository: zmkfirmware/zmk
          ref: v3.5.0
          path: zmk

      - name: Create ZMK Config Directory
        run: |
          mkdir -p /tmp/zmk-config/config
          cp -r zmk-config-notbroken/config/* /tmp/zmk-config/config/

      - name: Build Firmware
        run: |
          west init -l zmk
          west update
          west build -s zmk/app -d /tmp/tmp.M2UM4VapoI -b nice_nano_v2 -- -DZMK_CONFIG=/tmp/zmk-config/config -DSHIELD=murphpad -DZMK_EXTRA_MODULES=$GITHUB_WORKSPACE/zmk-config-notbroken
        env:
          GITHUB_WORKSPACE: /__w/zmk-config-notbroken/zmk-config-notbroken

      - name: Archive Firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: /tmp/tmp.M2UM4VapoI/zephyr/zmk.uf2